### ISSUE TITLE
Las balas no atraviesan el humo de la granada ralentizadora

### ISSUE THREAD

**Issue by Rohadgal** [lfeq/Class-Multiplayer-FPS#11]
Las balas no atraviesan el humo de la granada ralentizadora

**Comment by Rohadgal** [comment]
@lfeq puedes arreglar este asunto?

**Comment by lfeq** [comment]
Depende de mi humor

**Comment by lfeq** [comment]
> @lfeq puedes arreglar este asunto?

Depende de mi humor

**Comment by lfeq** [comment]
@Rohadgal Estaba de buen humor

**Comment by Rohadgal** [comment]
@lfeq se nota que ya hace menos calor
